# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

use_frameworks!
target 'MaterialCocoaPodTemplate' do

pod 'Alamofire', '~> 4.3'
pod 'Material', '~> 2.4'
pod 'SwiftyJSON', '~> 3.1'

end
